### ISSUE TITLE
Invalid example URL for loading projects from DB in README

### ISSUE THREAD

**Issue by hustodemon** [qwc-services/qwc-qgis-server#10]
Hello everyone,

when testing loading projects from the DB, I got a 404 from the qwc-qgis-server when using the suggested URL (`http://localhost:8001/qgis/pg/public/myproject`). Changing to `http://localhost:8001/ows/pg/public/myproject` worked.

It seems the URL_PREFIX had changed in the past, but the README was not updated.

Suggested fix: https://github.com/qwc-services/qwc-qgis-server/pull/9

**Comment by tpo** [comment]
I'm closing this ticket, since #9 was merged, I hope that's fine, otherwise please reopen with justification
