### ISSUE TITLE
intermittent log messages "QNetworkDiskCache::prepare() unable to open temporary file"

### ISSUE THREAD

**Issue by w0pr** [qwc-services/qwc-qgis-server#5]
I run sourcepole/qwc-qgis-server:3.28-plugins image from the docker services.

I am getting intermittent "QNetworkDiskCache::prepare() unable to open temporary file", especially when running config-generator.

```qwc-docker-qwc-qgis-server-1              |  QNetworkDiskCache::prepare() unable to open temporary file```

What might be the source of that? Do I need to configure the cache folder somehow? I did **not** specify a host volume for it.

I have set  SERVICE_UID: 1003 & SERVICE_GID: 1003 in docker-compose.yml, is there some permission issue?

I also opened same issue on [qwc2-demo-app](https://github.com/qgis/qwc2-demo-app/issues/457#issue-1740429324), close as appropriate.

**Comment by tpo** [comment]
Do you see any functional problems that are caused by this or is it "just a log entry"?

> I have set SERVICE_UID: 1003 & SERVICE_GID: 1003 in docker-compose.yml, is there some permission issue?

SERVICE_UID and SERVICE_GID should be set to the user that owns the checkd out files from the qwc-docker repo. is that the case?

**Comment by w0pr** [comment]
> Do you see any functional problems that are caused by this or is it "just a log entry"?

No, it is "just a log entry". However, I have no way of comparison performance, if this pointed to ineffective cache.

> > I have set SERVICE_UID: 1003 & SERVICE_GID: 1003 in docker-compose.yml, is there some permission issue?
> 
> SERVICE_UID and SERVICE_GID should be set to the user that owns the checkd out files from the qwc-docker repo. is that the case?

Yes. 
```uid=1003(qgis) gid=1003(qgis) groups=1003(qgis),4(adm),27(sudo),999(docker)```
